
name: Test GHA
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'The cdk command (deploy or destroy)'
        default: 'deploy'
        required: true
jobs:
  codebuild:
    runs-on: [self-hosted, linux, codebuild]
    steps:
    # Uses checkout@v2 to checkout the current repo
    - uses: actions/checkout@v2

  lambda:
    runs-on: [self-hosted, linux, lambda]
    steps:
    # Uses checkout@v2 to checkout the current repo
    - uses: actions/checkout@v2

  fargate:
    runs-on: [self-hosted, linux, fargate]
    steps:
    # Uses checkout@v2 to checkout the current repo
    - uses: actions/checkout@v2